name: Network Performance Monitor

on:
  schedule:
    - cron: '0 1,4,10 * * *'
  workflow_dispatch:
  push:
    paths:
      - 'ip.py'
      - 'requirements.txt'

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python ip.py
