name: Scrape and Save IPs

on:
  schedule:
    # 每小时执行一次爬取任务（UTC时间零点）
    - cron: '0 0/6 * * *'
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run scrape script
      run: |
        python main.py

    - name: 推送到public分支
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.KEY }}
        epository-name: Lbb886/ips
        branch: public
        folder: .
        commit-message: "Update IP lists"
