name: Scrape and Save IPs

on:
  schedule:
    # 每小时执行一次爬取任务（UTC时间零点）
    - cron: '0 0/1 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run scrape script
      run: |
        python main.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'Lbb886'
        git config --global user.email '2745592207@qq.com'
        git add ip.txt ipv6.txt
        git commit -m 'Update IP lists'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.key }}
